//= ./../../node_modules/jquery/dist/jquery.min.js
//= ./../../node_modules/swiper/swiper-bundle.min.js
//= ./libs/jquery.fancybox.min.js
//= ./libs/choices.min.js
//= ./libs/gsap.min.js

//= ./partials/main.js
//= ./partials/swiper-init.js
//= ./partials/tabs.js
// ./partials/tags-block.js
//= ./partials/courses-carousel.js
//= ./partials/tutorials-carousel.js
//= ./partials/recommend-carousel.js
//= ./partials/trip-carousel.js
//= ./partials/reviews-carousel.js
//= ./partials/products-carousel.js
//= ./partials/stock-carousel.js
//= ./partials/footer-accordion.js
//= ./partials/articles-carousel.js
//= ./partials/catalog.js
//= ./partials/status.js
//= ./partials/product-options.js
//= ./partials/filters.js
